name: CD

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    env:
      MSBUILD_EXE_PATH: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Enterprise\\MSBuild\\Current\\Bin\\MSBuild.exe"
    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.4
      with: 
        fetch-depth: 0
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.8.1
      with:
        dotnet-version: 5.0.x
    - name: Install dependencies
      run: |
        cd ./src/WebApiBolierplate
        dotnet restore
    - name: Build
      run: |
        cd ./src/WebApiBolierplate
        dotnet build --configuration Release --no-restore
    - name: IntelliCode Team Completions
      uses: microsoft/vs-intellicode@v1.0
      with:
        logs: debug
